#!/bin/bash

#Demo of desicion making

a=5
b=2
c=$(($a*$b))
let c=a*b

if [ $a -gt $b ]
then
  #Do something
  echo a greater than b
  let c=1
else
  echo a less than b
  let c=5
fi

#loop ten times 
while [ $c -le 10 ]: do
  echo Number $c
  let c++
done
